name: Python Calculator CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t calculator-app .

      - name: Run tests inside Docker
        run: docker run --rm calculator-app pytest -v

      - name: Run calculator demo
        run: docker run --rm calculator-app